# Generated by Django 2.2.6 on 2019-10-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
