# Generated by Django 2.2.6 on 2019-10-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20191019_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
