# Generated by Django 2.2.6 on 2019-10-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20191019_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tuijian', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('price', models.FloatField()),
                ('num', models.IntegerField()),
                ('ISBN', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('typeid', models.ManyToManyField(to='myadmin.Booktype')),
            ],
        ),
        migrations.CreateModel(
            name='BookImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='static/uploads/')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books')),
            ],
        ),
    ]
