# Generated by Django 2.2.6 on 2019-10-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_bookimgs_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('totalprice', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('paytime', models.DateTimeField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('select', models.IntegerField(default=0)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
    ]
