# Generated by Django 2.2.6 on 2019-10-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_cart_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='face',
            field=models.CharField(default='/static/myadmin/assets/img/timg.jpg', max_length=100),
        ),
    ]
